### ISSUE TITLE
User 'join date' is incorrect

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/support.bioconductor.org#1]
e.g., http://34.224.95.209/accounts/profile/1513/ shows me joining '4 days ago' but actually I've been a member for longer than that ;)

**Comment by lshep** [comment]
It seems like all joined dates might be 4 days ago. Mine shows this as well and I clicked on several random user accounts, all show 4 days

**Comment by Natay** [comment]
The auto_now_add parameter field was set to True in the date_joined field of the profile. 

I pushed out a bug fix on my branch, it will be merged with the main biostar branch on Wednesday.
