### ISSUE TITLE
Split tags and reduced number of tagged questions

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#10]
On the current support website, clicking on TAGS from the top page shows that "limma", "edgeR"  have been tagged 3782 and 1653 times respectively. There is only one "limma" tag and only one "edgeR" tag.

On the upgraded support website, the "limma" entry has been split into two, one with 2381 threads and one with 1370 threads.

Looking at the cgi-bin links for these pages suggests that the two limma tags are now "limma" and " limma" (with a leading space). All the old limma tags now have a leading space.

Likewise, there are now two "edger" tags, one with a leading space and one without.

Even combining the counts for the split tags, the upgraded site has a substantially reduced number of tagged questions for limma and edgeR.

**Comment by lshep** [comment]
the new site also has suggested tags for packages now to avoid the confusion and spacing issue.  This is probably also why in part maintainers were not always informed since tags were freeformed (along with typos and other issues)

**Comment by Natay** [comment]
This has been fixed in the newest push, the white spaces have been stripped and the split tags have been merged.
