### ISSUE TITLE
problems in asking a question

### ISSUE THREAD

**Issue by Gengiu-code** [Bioconductor/support.bioconductor.org#107]
Since yesterday, I couldn't send my question in Bioconductor forum. How can I solve the issue?

**Comment by lshep** [comment]
Could it be that there were non-ascii characters in the pasted output or a valid Bioconductor package tag was not selected?

**Comment by Gengiu-code** [comment]
The selected packages were on the menu list and I have changed two non-ascii characters that were in Italian language but still It doesn't work

**Comment by lshep** [comment]
ascii characters will be problematic and prevent posting.  I would ensure that there are no additional characters in the text or title.  It might help to reset the website cache in your browser as the error also might have been cached.

**Comment by Gengiu-code** [comment]
I have cleaned the cache and changed the language of error messages from ITA to ENG but still, I cannot post my question.

**Comment by lshep** [comment]
can you post the information here for us to investigate?

**Comment by Gengiu-code** [comment]
Ishep, now I have used this site to check the code https://pages.cs.wisc.edu/~markm/ascii.html
and I have found others non-ascii characters. I solved the problem and just posted the question. Thank you so much
