### ISSUE TITLE
Tagged questions ranked in inscrutable way

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#11]
On the current support site, clicking on "TAGS" then on "limma" brings up a list of 3723 results with most recently updated questions listed first.

On the upgraded site, doing the same thing brings up 2381 questions ranked in an undocumented way that doesn't appear to correspond to anything useful.

On the current support site, the tagged questions can be sorted in 8 different ways, of which update is the default. The updated site offers only 4 sorting options, none of which are very useful.

From my point of view, the main use of the tags was find recent questions corresponding to my packages. Now I can't do that.

**Comment by Natay** [comment]
We will look to add more sorting options but the odd grouping has been fixed. Tags questions are listed according to edit date

**Comment by gksmyth** [comment]
Thanks.

IMO the potentially useful sort options are (1) update, (2) creation and (3) votes, in that order. I doubt the other options are often used, if at all.

**Comment by Natay** [comment]
The sorting options have been added.
