### ISSUE TITLE
Only old tagged questions

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#12]
On the updated site, if I click on TAGS from the top page, then click on the first instance of "limma", all the questions shown are at least 6 years old.

If I click on "Limit" and choose "this year" then no results are shown.

Looking at the link at the browser link at the top of the page suggests that the new site has reset all the old "limma" to tags to " limma" (with a leading space).

**Comment by Natay** [comment]
This was fixed in the most recent push to the website, it was an issue with the extra white space in the tags like you mentioned.
