### ISSUE TITLE
User search still give strange results

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#14]
I raised an issue about user searches earlier today, which was closed without being completely fixed.

Searching for "Gordon Smyth" still finds 4 users with single-letter names in addition to the correct hit.

A search for "Gordon Smyth" in single or double quotes returns only the 4 users with single-letter names and doesn't return the correct hit.

**Comment by Natay** [comment]
Issue has been fixed, stemmed from the wrong database query being used ( __in vs __icontains ) and sanitizing quotes.
