### ISSUE TITLE
Bioconductor logo leading to Bioc landing page rather than support site landing page is confusing/annoying.

### ISSUE THREAD

**Issue by j-andrews7** [Bioconductor/support.bioconductor.org#15]
A minor complaint, but something that's bothered me for years. The Bioconductor logo header on the support site leading to the main Bioconductor landing page rather than the support site landing page is not expected behavior, in my opinion.

**Comment by mtmorgan** [comment]
I think this is my 'fault', and apologize for bothering you for years ;) I'm ok with the logo taking us back to the support site, rather than to bioconductor.org.
