### ISSUE TITLE
Inconsistency between preview and post for copied code / blockquotes

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/support.bioconductor.org#18]
It's pretty common for people to seemingly just copy/paste straight from an R terminal, and the preceding `>` leads to everything being in a block quote.  It's a bit annoying and I guess leads to a lot of manual post editing by the moderators.  It'd be really nice if we could catch that, but I can't see an easy strategy for doing this.  Maybe users will just copy into the boilerplate code block and that'll be sufficient.

However there's seems to be some discrepancy between the preview and the final output when I do a naive copy/paste e.g. a direct copy of this (once inside a code block, once outside)

```
> length(RNAcentralHits[[2]]) # No known ncRNA between positions 500000 and 550000 of chromosome D
[1] 0
> 
> tRNAfragment <- "UGCGAGAGGCACAGGGUUCGAUUCCCUGCAUCUCCA"
> centroidFoldPrediction <- predictSecondaryStructure(tRNAfragment, "centroidFold")
```

gives me the preview

![image](https://user-images.githubusercontent.com/971237/96556049-cf87d480-12b8-11eb-9171-d2834f52fe6f.png)

but this is the final post:

![image](https://user-images.githubusercontent.com/971237/96556361-2d1c2100-12b9-11eb-8609-25b3e5b7e046.png)

http://supportupgrade.bioconductor.org/p/p131907/

**Comment by Natay** [comment]
Thank you for letting us know !

This comes from the internal markdown parser competing with the html sanitizer, we will investigate further and push out a fix.

**Comment by Natay** [comment]
This issue has been fixed in the latest merge
