### ISSUE TITLE
Boilerplate text

### ISSUE THREAD

**Issue by jmacdon** [Bioconductor/support.bioconductor.org#2]
I can see the rationale for the boilerplate text for questions, although I am not completely sold on the idea. I'm betting we end up having all sorts of posts with the boilerplate text at the bottom, without having much effect on the quality of the posts. But I could be wrong.

However, I don't see the utility of including that in the reply, comment, or answer fields. The expectation should be that anybody who takes the time to do any of those things is already cognizant of how things work, and having to highlight and delete extraneous text in order to respond is more likely to be a barrier to engagement rather than helping to improve things.

**Comment by lshep** [comment]
valid point. considering how many recent complaints about post formatting we thought a template might be a good solution.  It can be removed at any time but we thought we would see if it helps or hurts.   I'm open to other opinions or suggested solutions.

**Comment by jmacdon** [comment]
I don't totally hate it, and it might actually help. I imagine there are two types of people who post - those that just don't know that they can format things, and those that don't care that they can format things. It will probably help with the former, I mean it's right there, but for the latter? Nah.

So if it can be removed at any time, and particularly if it can be removed from everything but the original posting box, I say let's give it a try.

**Comment by gksmyth** [comment]
Would be good to check the biolerplate text for typos.

Also the "r" following the three backticks is unnecessary and potentially confusing to a new user.

**Comment by lcolladotor** [comment]
Hi,

I think that a template text is useful. It can show how to do a few things, like how to format R code. From my test at http://supportupgrade.bioconductor.org/p/p131903/, I noticed a typo on the word `following`. Also, I thought that it could potentially be good to mention the `reprex` package. 

Here's also a much longer template https://github.com/lcolladotor/biocthis/issues/new?assignees=&labels=&template=issue_template.md&title=%5BBUG%5D+Your+bug+or+feature+request

Best,
Leo

**Comment by mtmorgan** [comment]
I kind of disagree on the reprex package -- great for users comfortable with reporting problems, but 'just another hurdle' for users struggling with how to use the software.

**Comment by lshep** [comment]
And we felt like a longer template would be a pain for users to delete if they didn't want to use it

**Comment by lshep** [comment]
@gksmyth   I believe there is language specific hightlighting so the r after the backtic is actually useful and relevant

**Comment by Natay** [comment]
Typo fixed and boilerplate text taken out of answers, replies, and comments.
