### ISSUE TITLE
Tags don't allow spaces

### ISSUE THREAD

**Issue by lshep** [Bioconductor/support.bioconductor.org#20]
While we don't want pre or post trailing white space, I think we want users to be able to have spaces for free form tags.  Currently a space will indicate an end of tag  ie...  trying to do `support site`  when I type ends up two tags `support` `site

**Comment by Natay** [comment]
This issue has been fixed in the recent update, we had disallowed spaces in an attempt to shorten user tags. 

They have bee put back in.
