### ISSUE TITLE
How to watch everything?

### ISSUE THREAD

**Issue by hpages** [Bioconductor/support.bioconductor.org#23]
Before the update, there was a setting that I used that would allow me to watch everything (can't remember the name of the setting). I don't seem to be able to find it with the site update. So I started to add many tags to my "Watched Tags" list in my profile. However after adding about 35+ tags, and being not even halfway of all the tags I want to add, I started to realize how inconvenient the whole process was. It's going to be much easier if I can watch everything and skip all this tag management process.

How can I do this with the new version of the site?

Thanks

**Comment by Natay** [comment]
Thank you for letting us know!

This is essentially a digest of the site and we have that in the works and nearly complete.

It will send a notification with a summary of the posts for day, week, or month ( depending on your digest preferences ).

**Comment by lshep** [comment]
On the old site we had digests inactive for some reason -- we are reinstating it.

**Comment by hpages** [comment]
I was more thinking of getting all incoming questions/answers/comments as emails in real-time. This is how I had it set up with the old site. It's easier for me to follow activity thru my email client. Thanks @Natay @lshep for looking into this.

**Comment by Natay** [comment]
That can be added as an extra option to the existing notification dropdown in the profile.  

Just to elaborate, this would send you an email for every post created regardless of tag.

**Comment by hpages** [comment]
Yep, exactly! Even for comments added to old posts. Thanks a lot!

**Comment by Natay** [comment]
We have added a "Digest Preferences" dropdown with a mailing list option that sends an email for every post.

You will need to edit your digest preferences dropdown to 'mailing list mode' to get this feature.

**Comment by hpages** [comment]
Hi @Natay ,

Seems to work like a charm. Thanks for adding this so quickly!

The emails are sent from `hello@biostarhandbook.com`. Is that expected? FWIW with the old site, they were sent from `noreply@bioconductor.org`. I'm fine with either. Makes no difference to me, as long as I can rely on the From field to define my filters in Thunderbird.

Thanks again,
H.

**Comment by Natay** [comment]
No problem. 

We had used different email settings after the upgrade, the sent from email will change back to `noreply@bioconductor.org` by Tuesday.

**Comment by mtmorgan** [comment]
I have digest preference set to "Email for every new thread (mailing list mode)" and Notifications set to 'Email', but don't receive notifications. I'll re-open, even though this could be 'user error'.

**Comment by Natay** [comment]
@mtmorgan  can you check the spam folder ? Gmail put the first couple I received in the `promotions` tab.

**Comment by Natay** [comment]
No problem
I am reopening this while testing things out more, it will be closed by tomorrow.
