### ISSUE TITLE
how can I post WGCNA issue?

### ISSUE THREAD

**Issue by shangguandong1996** [Bioconductor/support.bioconductor.org#24]
Hi, Dear developer.
Thanks for your update about support.bioconductor.org. But I found a little problem about WGCNA.
I want to post a issue about WGCNA, but I found 
![图片](https://user-images.githubusercontent.com/22555126/96967409-0fadb800-1542-11eb-81b8-bca030501c7b.png)

I know WGCNA is not in the bioconductor list, But the author did answer some question about WGCNA. 
![图片](https://user-images.githubusercontent.com/22555126/96967569-4b488200-1542-11eb-83c2-a8b4df938900.png)

So I am wondering whehter I can have some ways to post a problem about WGCNA in the bioconductor support

**Comment by lshep** [comment]
In talking,  we are adding WGCNA and CRAN as acceptable tags to post

**Comment by lshep** [comment]
If there is a related Bioconductor package that is also used in conjunction than you should post both the Bioconductor package and WGCNA.

**Comment by lshep** [comment]
You will be able to tag WGCNA within the next 10 min

**Comment by lshep** [comment]
Thanks for the report @shangguandong1996 -- this should be resolved now and you should be able to post with WGCNA

**Comment by shangguandong1996** [comment]
Thanks :)
