### ISSUE TITLE
Mobile styling

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/support.bioconductor.org#25]
This is purely cosmetic, but I notice in the mobile styling that the overlay on the left-hand menu has rounded corners, but they're square on the right-hand menu.

<img src="https://user-images.githubusercontent.com/971237/97007096-269fda80-1541-11eb-8af6-d41365fb5c5c.png" height=500> <img src="https://user-images.githubusercontent.com/971237/97007102-28699e00-1541-11eb-96db-694858e88304.png" height=500> 

Subjectively, there also seems to be a lot of white space around the content.  There's both the left/right margins around the whole page, and then some padding on the container for the posts.  On my (admittedly old) phone it makes the content feel very cramped, and a bit of a waste of the full width of the screen.

**Comment by Natay** [comment]
I agree, the mobile view can get cramped. 

We will fix up these inconsistencies and push out an update.

**Comment by Natay** [comment]
We have pushed out an update dealing with the extra padding and rounded corners.

**Comment by grimbough** [comment]
Thanks a lot, look much better now IMO.
