### ISSUE TITLE
Old threads from email list days now reformated as single paragraphs

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#28]
Previously, posts from the email list days were preserved in a verbatim/preformatted format. All the old questions and answers are now run into single paragraphs will all blank lines and line ends removed, which makes them very hard to read.

Here is one example:
https://support.bioconductor.org/p/5144/

**Comment by Natay** [comment]
Thanks for lettings us know, this issue has been fixed.
