### ISSUE TITLE
Votes always shows page 1

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#29]
Clicking on "Votes" show a page of my posts that have been upvoted. In my case it says "Page 1 of 42" and an arrow is shown to go to the next page. Clicking on the arrow to go to the next page shows `votes/?page=2&` in the browser address box but page 1 is still shown. Now matter which page is chosen, the same page 1 is always shown.

**Comment by Natay** [comment]
Thanks for letting us know, this issue has been fixed.
