### ISSUE TITLE
Clicking on tags does nothing

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/support.bioconductor.org#3]
Clicking on the tags appears to do nothing.

That's on both the 'tags' page and underneath a post.  It just highlights the word with a black square (only in Chrome, not in Firefox), but nothing happens.

It looks like the tag URL is fine, hitting "Open in a new tab" does the job and I get the appropriate posts e.g. http://34.224.95.209/?tag=biomart  but it doesn't respond to a left-mouse click.

**Comment by Natay** [comment]
Thanks for the bug report @grimbough !

We fixed it in the most recent push, there was a conflict in an html attribute used.
