### ISSUE TITLE
Typing is very laggy

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#30]
When one posts a question or answer, there is a lag between typing a key and seeing the character appear on the screen. (I'm talking about the input text here, rather than the preview window, although the lag is for both.)

The lag is long enough to make the upgraded site disconcerting to use. I don't notice a similar lag when using Biostars or other forums. A lag was an issue with Bioc Support when it first moved to a web forum many years ago, but somehow it was fixed long ago.

I don't know whether the lag is partly caused by the real-time preview window. As an experienced user, I would really like the option of turning off the preview window. It crowds the screen without being very useful, especially for longer posts.

**Comment by gksmyth** [comment]
I find that the only way I can use the website at the moment is to compose answers in my own text editor separate to the website, and then paste the answer in a block. Otherwise the slow typing echo is just too annoying and time consuming.

**Comment by Natay** [comment]
Thanks for letting us know @gksmyth and your patience, we will prioritize this and push out a fix.

**Comment by Natay** [comment]
This issue has been fixed, thanks again for letting us know. 

We handled it by making the html preview work asynchronously
