### ISSUE TITLE
Almost all votes now dated as 1 day, 11 hours ago

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#31]
When I clock on "Votes" I see a list of votes, accepts and bookmarks that my posts have received. The votes from the last 24 hours are correctly dated, but all older votes are now dated as having occured 1 day, 11 hours ago. Amongst other things, this means that the votes are unpredictably ordered because they all share the same time. So the first page doesn't show the most recent votes.

**Comment by Natay** [comment]
This issue has been fixed, the date field in the Vote table needed the auto_now_add parameter removed.
