### ISSUE TITLE
Extra info on preview on bioconductor.org

### ISSUE THREAD

**Issue by lshep** [Bioconductor/support.bioconductor.org#35]
So cross referencing this reported issue for the main bioconductor.org site  [issue](https://github.com/Bioconductor/bioconductor.org/issues/74) 

It seems like the previews are taken from the following RSS feed 
`https://support.bioconductor.org/feeds/latest/`

And the muddy data of `Comment: Comment:` and the like is stemming from the defined `<title>` on that page.  I know we corrected this issue on the support.bioconductor.org site for the `recent` post listing and I was wondering if the same filter can be applied to the results displayed on the feed or if it would have to be done in the biocondcutor.org parsing of the page --

**Comment by Natay** [comment]
Thanks for letting us know, we took out the extra prefix in the title.

The RSS feeds have correct titles now.
