### ISSUE TITLE
Emails received in 'mailing list mode' don't contain the name of the poster in the From field

### ISSUE THREAD

**Issue by hpages** [Bioconductor/support.bioconductor.org#36]
Here is what I see (in Thunderbird) for the emails sent by the new site (no poster name in the From field): 

![mailing_list_mode_new_site](https://user-images.githubusercontent.com/8810451/97399840-373ab280-18ab-11eb-9230-7d8bd72e59d6.png)

-----------------------------------------------------------------------------------------

Here is what I was seing with the old site (the name of the poster was included in the From field):

![mailing_list_mode_old_site](https://user-images.githubusercontent.com/8810451/97399854-3e61c080-18ab-11eb-9e4b-aa45db9601e6.png)

For example, the highlighted email was sent from `Michael Love [bioc] <noreply@bioconductor.org>`.

I hope this can be restored. It's very useful to be able to quickly identify the author of a post from the email interface. Thanks!

**Comment by Natay** [comment]
Thanks for letting us know, and for the detailed report.

We will looking this and push out a fix.

**Comment by Natay** [comment]
This issue has been fixed.

**Comment by hpages** [comment]
Perfect! Thanks for the quick fix.
