### ISSUE TITLE
Displayed "age" of many old posts and their answers is incorrect

### ISSUE THREAD

**Issue by hpages** [Bioconductor/support.bioconductor.org#37]
See for example:

![incorrect_displayed_ellapsed_time](https://user-images.githubusercontent.com/8810451/97491848-f761e280-191f-11eb-88f7-6b45f6ed830c.png)

Here is the thread: https://support.bioconductor.org/p/87709/ The original post and Michael's answer are both from Oct 1, 2016. That's 4 years ago. But for some reason they are reported as being 7 months old and 8 weeks old, respectively.

Another example is: https://support.bioconductor.org/p/102396/ The post is from Oct 30, 2017, but displayed age is 14 days. And Martin's accepted answer is from Nov 1st, 2017, but displayed age is 1 hour.

That seems to be a problem for many old posts but not all of them. For example the displayed age for https://support.bioconductor.org/p/110890/ (2.3 years ago) is correct (the post is from July 10, 2018).

Thanks

**Comment by Natay** [comment]
Thanks for letting us know, 

The "age" you are referring to ( the one seen in the user box) is the last seen time for that user. 

The posts age is displayed to the right of the add comment button.

**Comment by hpages** [comment]
Indeed! I should have known that. Sorry for the noise.

I guess my confusion probably comes from the fact that this info is displayed as `visited 1 hour ago` in the USERS section, or as `Last seen: 1 hour ago` in a user profile. Whereas in a thread it's displayed "naked" like the age of the question itself. Also the fact that it's displayed before/above the user name instead of after/below is a little bit misleading.

Would it be possible to make this clearer? E.g. precede the time elapsed since the last visit with `Last seen` like in the user profile, and maybe move this below the user name.

Also, unless there's a difference between "seen" and "visited", maybe use the same term everywhere.

Thanks and sorry for being such a nitpicker ;-)
