### ISSUE TITLE
Double clicking on a question acts as though 'edit' chosen, rather than selecting line

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/support.bioconductor.org#38]
The common short-cut of double or triple clicking on a line of text to select a word or the entire line (e.g., the line starting with `trying URL` in https://support.bioconductor.org/p/p132470/) instead changes the question to 'edit' mode (as though the 'edit' link were chosen). If I do this while writing a comment or answer, the comment or answer is lost.

**Comment by Natay** [comment]
Thanks for letting us know, this is an added behavior triggered on double clicks. We will remove this behavior.

**Comment by Natay** [comment]
This behavior has been corrected.
