### ISSUE TITLE
Suggestion: clarify the meaning of the "age" displayed below user names in threads

### ISSUE THREAD

**Issue by hpages** [Bioconductor/support.bioconductor.org#39]
This is a follow-up of issue #37.

It's not immediately clear that the elapsed time displayed in a thread under a user name is the elapsed  time since the user's last visit. Unlike in the USERS section where something like `visited 1 month ago` is displayed, or in a user profile where `Last seen: 1 month ago` is displayed, here the elapsed time is displayed "naked" (e.g. `1 month ago`), like the age of the question itself which is displayed in a much less prominent manner. Also the fact that it's displayed before/above the user name instead of after/below somehow contributes to the confusion.

My suggestion would be to precede the time elapsed since the last visit with `Last seen:` like in a user profile and move this below the user name.

Also, unless there's a difference between "seen" and "visited", maybe the same term could be used everywhere.

Obviously not a priority but sounds like a simple change that could substantially improve clarity/readability.

Thanks

**Comment by Natay** [comment]
Good suggestion @hpages , we will add this to the next update of the site.

**Comment by Natay** [comment]
This feature has been added to the site

**Comment by hpages** [comment]
Fantastic!
