### ISSUE TITLE
Populating the Similar Posts section

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/support.bioconductor.org#4]
Does the "Similar posts" section on the right-hand side ever get populated?  I've not seen anything appear there, even for a post like "[New Package Submission Deadline for Bioc Release 3.12](http://34.224.95.209/p/134219/)", which must be pretty similar to one from 6 months ago.

![image](https://user-images.githubusercontent.com/971237/94797605-a7efcb80-03e0-11eb-8b8c-d0857190be6f.png)

**Comment by Natay** [comment]
Thanks for letting us know, this happened because the search index is not populated yet. 

Similar posts are now populated.
