### ISSUE TITLE
Moderation choices

### ISSUE THREAD

**Issue by jmacdon** [Bioconductor/support.bioconductor.org#41]
It used to be possible for a moderator to move a comment to an answer, which was IMO a nice feature. Changing an answer to a comment/reply would be nice as well, but I understand if that is easier said than done.

**Comment by lshep** [comment]
I think you might be able to use the drag and drop option to switch a post level?

**Comment by Natay** [comment]
You can drag and drop posts like Lori described using the grab icon 
![Screen Shot 2020-11-06 at 11 54 17 AM](https://user-images.githubusercontent.com/16328794/98393200-f5d2a180-2026-11eb-9acc-4bfe96f8bd18.png)

To move a comment into an answer, drop it into the answer box.
