### ISSUE TITLE
Receiving notifications about tags I'm not following

### ISSUE THREAD

**Issue by liz-is** [Bioconductor/support.bioconductor.org#44]
Hi,

I've received a couple of emails that say they are about "Activity on a tag you are watching on support.bioconductor.org", however neither of them was actually related to any tags I'm following.

The only tag I'm following is the package I maintain, `genomicinteractions`. 

I got an email today about [this post](https://support.bioconductor.org/p/p132778/) and on Friday about the new comment on [this post](https://support.bioconductor.org/p/102147/#p132675).

**Comment by llrs** [comment]
It happened the same, to me I received an email about a post tagged with `R` and `EBImage`, while I am only following `BioCor` and `biocor`

**Comment by lshep** [comment]
@Natay  -- also along with this I seemed to have gotten duplicate emails this morning too...

**Comment by Natay** [comment]
Thanks for letting us know, we will push out a fix.

@lshep are the duplicate emails for the same watched tags?

**Comment by lshep** [comment]
I'm receiving two per response for the EBImage/R issue --

**Comment by Natay** [comment]
This issue has been resolved, we were doing a __contains search for the watched tags and needed to filter for exact words instead.
