### ISSUE TITLE
Emails sent are no longer properly formatted

### ISSUE THREAD

**Issue by hpages** [Bioconductor/support.bioconductor.org#45]
Hi,

On November 5, the emails sent by the support site have changed from this:
![Screenshot from 2020-11-11 13-50-55](https://user-images.githubusercontent.com/8810451/98868738-74fc1700-2425-11eb-91a8-b5b5883066ed.png)
to this:
![Screenshot from 2020-11-11 13-51-27](https://user-images.githubusercontent.com/8810451/98868752-7cbbbb80-2425-11eb-8f4b-ede945f5b19b.png)

Is this intended?

The old formatting was nicer and contained useful links that have disappeared in the new formatting.

Thanks

**Comment by Natay** [comment]
Thanks for letting us know , we switched the emailing backend and this was not an intended effect. 

We will investigate and push out a fix.

**Comment by Natay** [comment]
This issue has been fixed, thanks for your patience.
