### ISSUE TITLE
Some inconsistencies while searching

### ISSUE THREAD

**Issue by llrs** [Bioconductor/support.bioconductor.org#46]
When [searching](https://support.bioconductor.org/post/search/?query=No+gene+can+be+mapped+in+Cluster+profiler) for a question I got some weird results:
 - If I search with "No gene can be mapped in Cluster profiler" (the exact title of [this question](https://support.bioconductor.org/p/p132808/)) an answer to said question appears on the 14th position of the first page and the question itself on the 16th.
 - The results display an incorrect number of views, they only show 0, 1, 2 or 3. But when one clicks on the question it shows: "34 views".

**Comment by Natay** [comment]
Thanks for letting us know @llrs .

The searches are ordered by the last edit date so answers and comments most recently edited are meant to show up higher.

The vote, reply and view counts come from the search index and when that post was being indexed it had said counts. As the post gets more interaction, the real database values change but the index does not.

**Comment by llrs** [comment]
Could that sorting mechanism be exposed to the user? Sometimes I search only questions and sometimes only answers. 
If the search index doesn't show the accurate view counts, maybe don't show them?

**Comment by Natay** [comment]
Yeah, we will add a search sorting feature and take out the counts for the reason you stated.

**Comment by Natay** [comment]
We added a sorting dropdown to the searches and took out the counts.

Let us know if we need to add to or clarify the dropdown.

**Comment by llrs** [comment]
Not sure whether the update is working. The dropdown menu didn't change the search results order on both Firefox and Chrome.

**Comment by lshep** [comment]
You might try refreshing your cache?

**Comment by Natay** [comment]
We will investigate further and push out an update, some results have the same ordering for all sorting options but that is probably not the case here.

**Comment by llrs** [comment]
@lshep refreshing the cache that didn't work (that's why I also tested in two different browsers and in private windows)
