### ISSUE TITLE
CTRL+RETURN doesn't do anything

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#47]
When one edits a previous post, a line appears under the edit box saying

"Tips: CTRL+ENTER to submit the form. ESC to cancel. Double-click to edit post. Markdown accepted."

This line contains 4 tips. Two of them seem correct and two of them seem either wrong or ineffective.

ESC does indeed cancel the edit but CTRL+ENTER doesn't do anything.

I have no idea what "double-click to edit post" is intended to mean in the context of already editing a post. I know of no context on the support site when double-clicking on anything would edit a post.

**Comment by mtmorgan** [comment]
For what it's worth, originally, double clicking on a post while composing and answer did do something -- overwrite the answer I was trying to write! -- but this has been fixed https://github.com/Bioconductor/support.bioconductor.org/issues/38.

**Comment by Natay** [comment]
Thanks for letting us know, we will fix up the inconsistencies with the tips and push out a fix.

**Comment by Natay** [comment]
We fixed the tips and enabled CTRL + RETURN to enter forms.
