### ISSUE TITLE
Creating an answer and edit an answer aren't the same

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#48]
This isn't a bug but just an inconsistency that seems strange.

When one edits an existing answer one is presented with two buttons ("Save" and "Cancel") and a line of "Tips" including the shortcut key "ESC" to cancel the edit.

When one creates an answer, there is only one button ("Submit") and no tips or shortcut keys. The ESC key doesn't cancel the answer. Indeed there isn't clear how to cancel the answer without closing the entire browser page.

Perhaps the difference in the two interfaces a intended feature but, from a user point of view, editing an answer and adding an answer feel like the same operation and would probably benefit from having essentially the same interface.

Similarly, it is beneficial to have two terms "Save" and "Submit" for almost the same thing?

**Comment by Natay** [comment]
Thanks for letting us know, we pushed out an update.

1. Tips and shortcut keys are present for creating and editing an answer. 
2. Buttons are named the same
