### ISSUE TITLE
Search only seems to find ancient posts

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/support.bioconductor.org#5]
The search functionality doesn't seem to work properly right now.  

I get some results for "Bioconductor" or "limma", but nothing for "DESeq2" or "biomart".  

![image](https://user-images.githubusercontent.com/971237/94797938-2e0c1200-03e1-11eb-8f78-3151d485d5c8.png)

It looks like the results I get are all from posts at least 16 years old.

**Comment by Natay** [comment]
Thanks for letting us know, we had indexed a small sample to make sure things functions. All posts are now indexed and searchable.
