### ISSUE TITLE
Replies vs Answers vs Comments

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#50]
Biostars and the old Bioc Support site both counted the number of answers to each question, which seemed to me to be the right thing to count.

The Upgraded Bioc Support now counts the number for "Replies" to for each message and I don't understand what a "Reply" is.

Biostars and the old Bioc Support have the following terminology:
1. A reply to a top-level message is an "Answer".
2. A comment on a top-level message is a "Comment".
3. Any lower-level comment (a comment on a Comment or a Comment on an answer) is a "Reply".

Biostars and the old Bioc Support site count the number of Answers each post has received. If a Question hasn't been closed or received an Answer, then we would conclude the Question has not been dealt with. They don't count comments or replies except when counting the total activity level for a community member (total number of posts by that community member).

The Upgraded Bioc Support site now counts the number of "Replies" each Question has received, but I don't know what a reply is or how they are counted. It doesn't seem to concide with the old terminology or with anything else I can match it up with.

**Comment by lshep** [comment]
The color coding represents whether an answer has been given or not.  The color turns from green to blue when the question received an Answer. 
Personally I feel like the count should reflect at the very least comments to indicate if there has been any activity on the issue but I would gladly take other Bioconductor users opinions on what the correct behavior should be

**Comment by mtmorgan** [comment]
I guess we're talking about the count that appears in the boxes to the left of each question on a page like https://support.bioconductor.org.

I like the idea of Replies = Answers + Comments. This provides an indication of overall activity. It also captures the situation that sometimes a comment on a question serves effectively as an answer -- did you update your packages to their current version? / yes now it works. If the idea was to report just the number of answers, then probably a better name for the label would be 'Answer / Answers' rather than 'Reply / Replies'. StackOverflow reports answers, but there the layout and word limit on comments means that comments less commonly play the role of answers.

As Lori mentions there are other indications of 'answers' (green versus blue box) and 'accepted answers' (white versus yellow text).

**Comment by gksmyth** [comment]
@mtmorgan I take it from your comment that the Replies are currently defined as Answers + Comments. That is not always what is currently displayed (Issue #49).

I am personally very much of a StackOverflow point of view, that Answers are answers and Comments are just for prompting the poster to clarify their question or answer. IMO the aim of the community should be to achieve an accepted answer for each question rather than confusing mess of comments.

Biostars isn't quite as tightly organized as StackOverflow, but it still is Answer orientated.

I view a thread having a lot of comments as a sign of chaos. The question didn't include enough information so comments had to be added to prompt for more information. Or the question was off topic. Or the poster didn't understand the answer so asks for clarification (good) or just repeats the question again (bad). Or the poster asks follow up questions different from the original question. Or third parties add further questions of tenuous connection to the original.

IMO the reason why comments don't serve as answers on StackOverflow is that StackOverflow has a strong clear policy discouraging it. If you treat comments and answers as being on the same level, then they will be.

Anyway, now that I know the Biocore team is discussing the current terminology I won't argue over it. As long as the terminology and philosophy of the site is consistent, that's the important thing.

**Comment by Natay** [comment]
Just an FYI -- @gksmyth Martin is correct, Replies are Answer + Comments. 
The issue you mentioned ( #49) comes from the counts being incorrectly recomputed after a child post has been deleted. 
Fixing #49 issue will not change the complaint here, Replies will still be Answers + comments.
