### ISSUE TITLE
Regular users cannot delete their comments on the forum

### ISSUE THREAD

**Issue by RamRS** [Bioconductor/support.bioconductor.org#51]
Unlike on Biostars, regular users such as myself cannot delete the comments/posts that we create. Disallowing deletion is not a good idea, as I've seen users on Biostars resort to extreme measures like redacting content or replacing it with gibberish when they really want the content gone.

I think users should have the power to delete their content on the forum - i.e. they should have the delete (and maybe even the Close) option under moderate.

**Comment by Natay** [comment]
Thanks for letting us know, we will add this functionality.

**Comment by Natay** [comment]
This has been fixed in the most recent update of the site.
