### ISSUE TITLE
Login window not displaying

### ISSUE THREAD

**Issue by smgogarten** [Bioconductor/support.bioconductor.org#52]
On Google Chrome Version 86.0.4240.198, Mac OS X 10.11.6, clicking "Log In" fails to display the box for entering email/password:
![Screen Shot 2020-12-08 at 12 40 43 PM](https://user-images.githubusercontent.com/2028958/101539010-b1eaf900-3952-11eb-9a7a-5ce84015799a.png)

Firefox on the same OS displays the login window correctly.

**Comment by Natay** [comment]
Hey @smgogarten , Thanks for letting us know. 

Can you clear your cache and see if that fixes the issue?

**Comment by smgogarten** [comment]
Clearing the cache and restarting the browser did not help.

**Comment by Natay** [comment]
We have made changes and deployed recently, has this problem persisted?
