### ISSUE TITLE
endpoint api for website badge doesnt display proper counts

### ISSUE THREAD

**Issue by lshep** [Bioconductor/support.bioconductor.org#54]
I tried a small test file and included packages that are fairly active (deseq2) but it gives 0 for answer and comment , yet I think accurate for total: 
```
irb(main):005:0> my_hash = JSON.parse(temp.body)
=> {"bgeecall"=>{"answer_count"=>0, "comment_count"=>0, "total"=>0}, "deseq2"=>{"answer_count"=>0, "comment_count"=>0, "total"=>243}, "packfinder"=>{"answer_count"=>0, "comment_count"=>0, "total"=>0}, "rsweep"=>{"answer_count"=>0, "comment_count"=>0, "total"=>0}, "summarizedexperiment"=>{"answer_count"=>0, "comment_count"=>0, "total"=>2}}
irb(main):006:0> my_hash["deseq2"]
=> {"answer_count"=>0, "comment_count"=>0, "total"=>243}
```

**Comment by lshep** [comment]
Looks like this was updated. Just wanted to verify:
```
irb(main):009:0> my_hash["deseq2"]
=> {"answer_count"=>256, "comment_count"=>679, "total"=>240}
```
I can interpret this as  240 total questions in the last 6 months.   Of those 240 questions there are 679 total comments  and 256 total answers being that there can be more than one answer/comment per questions.

Trickier -- is there a way to filter so the count is only 1 answer per questions  -- and/or if its easier (probably is) can we have the number of non-answered questions posted and I do the math? This may only happen for a handful of well used packages where there are multiple answers -- but I think on the landing pages of packages it might be more meaningful of display as I anticipate the backlash of how can there be  more answers than questions.

**Comment by lshep** [comment]
We have a team meeting this afternoon -- I'll demo my badge code and get their opinions on the counts and let you know their thoughts.

**Comment by lshep** [comment]
Talking with the team --  they agreed with my original assessment -- is there a way to count only one answer per post as answer instead of complete total  OR  could you give me a count of how many do not have an "answer" and I could do the math backwards from the total count?

**Comment by Natay** [comment]
Yeah not a problem, we can return one in the answer/comment counts if it has any.

an example output will be:

```
irb(main):009:0> my_hash["deseq2"]
=>  {"answer_count"=>1, "comment_count"=>1, "total"=>240}
```

**Comment by lshep** [comment]
That's not exactly right either... Maybe we can discuss next wed

**Comment by Natay** [comment]
This feature has been pushed out

**Comment by lshep** [comment]
The small file I was using for testing Justpkgs.txt with valid Bioconductor packages
```
DESeq2
SummarizedExperiment
topGO
miRNAtap
BSgenome.Hsapiens.UCSC.hg38
icetea
```
When I run the code that was semi working before but not right counts it now ERROR
```
res = RestClient.post("https://support.bioconductor.org/api/tags/list/", :tags => File.new("/home/shepherd/Justpkgs.txt"))
>  my_hash = JSON.parse(res.body)
=> {"error"=>"Error: operator does not exist: character varying = integer\nLINE 1: ...m_post\".\"answer_count\" > 1 AND \"forum_post\".\"uid\" IN (SELECT...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.\n"}
```

**Comment by Natay** [comment]
This feature has been fixed
