### ISSUE TITLE
Bookmarks only for toplevel question

### ISSUE THREAD

**Issue by ATpoint** [Bioconductor/support.bioconductor.org#55]
Currently there is a bug towards bookmarking. When I bookmark a toplevel question itself it gets displayed as expected in my `Bookmarks` section, but when I bookmark an answer I do not find it back in `Bookmarks`, the section stays empty.
Being on macOS10.14 with Chrome Version 88.0.4324.96 (Official Build) (x86_64)

**Comment by Natay** [comment]
Thank you for letting us know @ATpoint , we will push out a fix for this

**Comment by Natay** [comment]
This issue has been fixed in the recent push.

**Comment by ATpoint** [comment]
Thank you, can confirm it works now as expected.
