### ISSUE TITLE
"Answer" button missing on mobile site

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/support.bioconductor.org#57]
When viewing the site on a mobile device I don't see an answer button at the bottom of a question.  I can create a comment, but not an answer. Here's a screen shot of how it looks on my phone:

![Screenshot_20210221-093040](https://user-images.githubusercontent.com/971237/108634263-1c530600-7479-11eb-869b-2fb3ae5f9e8d.png)

Thanks for all the hard work on the site.

**Comment by Natay** [comment]
Thanks for letting us know, we will take a look and push out a fix

**Comment by Natay** [comment]
This issue has been fixed
