### ISSUE TITLE
Weird results with parentheses in code blocks

### ISSUE THREAD

**Issue by jmacdon** [Bioconductor/support.bioconductor.org#6]
I can't replicate this on the upgrade site, but then I've never seen it on the current site either, so wanted to report.

This is https://support.bioconductor.org/p/134455/#134464 in particular the second code block I submitted, which looks like

![image](https://user-images.githubusercontent.com/5940924/95219716-b6b0f680-07c3-11eb-8c6f-93ced12412fd.png)

But this was written as

![image](https://user-images.githubusercontent.com/5940924/95219795-caf4f380-07c3-11eb-976a-eb2337b048c5.png)

so I am mystified as to where the opening parentheses went.

**Comment by jmacdon** [comment]
If I add a space after the leading parenthesis it is visible

![image](https://user-images.githubusercontent.com/5940924/95232735-e5829900-07d2-11eb-9567-2bfb1893ae6a.png)

**Comment by Natay** [comment]
Thanks for letting us know! 

This is an issue with the markdown parser used in the old code base, we will continue to investigate it on that branch.
