### ISSUE TITLE
Error when tagging users via "@"

### ISSUE THREAD

**Issue by ATpoint** [Bioconductor/support.bioconductor.org#62]
Following error comes up when I try to tag someone / add username to a comment with @username.
Happens right after typing the "@".

<img width="391" alt="Screenshot 2021-03-31 at 20 53 19" src="https://user-images.githubusercontent.com/21218078/113196060-5925d000-9263-11eb-9f31-0d8a03ffd0bc.png">

**Comment by Natay** [comment]
We pushed out a fix for this. 

We changed how the handles work, they need to be explicitly set in the profile now before being accessible to other users.
