### ISSUE TITLE
Sidebar URLs are all `**MISSING**`, breaking this feature

### ISSUE THREAD

**Issue by RamRS** [Bioconductor/support.bioconductor.org#63]
Hi,

The sidebar on bioC support is broken, because each URL seems to have be just `**MISSING**`. Please see attached screenshot:

![](https://i.ibb.co/QX7dht2/image.png)

**Comment by Natay** [comment]
We had to reset the search index, some cached sidebars will have this symptom until the index is fully rebuilt.

**Comment by Natay** [comment]
Correction to my previous comment, it was a simple template issue that has been fixed.
