### ISSUE TITLE
Informative titles for search engine results?

### ISSUE THREAD

**Issue by llrs** [Bioconductor/support.bioconductor.org#64]
When searching using google, duckduckGo or other search engines the results of the site don't have an informative title of the question just [Bioconductor Forum](https://www.google.com/search?q=RankProd+site%3Asupport.bioconductor.org+paired+analysis). It would be nice if the title of the question showed up, it would help to find the results.

**Comment by Natay** [comment]
Thanks for letting us know, we will push out a fix for this asap.

**Comment by Natay** [comment]
This issue has been fixed in recent deployments.
