### ISSUE TITLE
admin page quirks

### ISSUE THREAD

**Issue by lshep** [Bioconductor/support.bioconductor.org#66]
when searching the admin page  the email section search does not appear to give accurate results. Unless this is delayed, when I added a test new user it was not appearing in this search but would appear when searching under the authentication and authorization email search.  

Also not sure if we turned off subscrptions but when you navigate to the emailers subscription section it has a server error message

**Comment by Natay** [comment]
The accounts information is found in authentication and authorization of the admin table, the latter issue has been fixed.
