### ISSUE TITLE
welcome email updates

### ISSUE THREAD

**Issue by lshep** [Bioconductor/support.bioconductor.org#67]
Title of email :    `[biostar-engine] Welcome to Bioinformatics Recipes!`

body needs updating: 

```
To verify your account belonging to shepherl@gmail.com, click the link below:

https://support.bioconductor.org/accounts/verify/MjUyMjY/akty12-8360516834aee88900935a69c2b453ce/

If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

Sincerely,

The Biostar Team
```

**Comment by Natay** [comment]
This issue has been fixed.
The templates are found in  `themes/bioconductor/templates/accounts/email_verify.html` and `themes/bioconductor/templates/accounts/email_verify_subject.md`
