### ISSUE TITLE
Title of the support site

### ISSUE THREAD

**Issue by hpages** [Bioconductor/support.bioconductor.org#68]
The title is "Bioinformatics Answers", like for the Biostars site.

It shows up on the top bar of the browser:

![Screenshot from 2021-04-21 22-05-23](https://user-images.githubusercontent.com/8810451/115658513-c3271780-a2ed-11eb-8c8b-23b67b81bcf6.png)

This comes from the HTML header:
```
<head>
    <title>
    Bioinformatics Answers
    </title>
    ...
```
Can this be changed to "Bioconductor Support Site"?

Thanks,
H.

**Comment by lshep** [comment]
Yes.  This is consistent with some of the email formatting that we have to update as well. thanks for reporting

**Comment by Natay** [comment]
Thank you for letting us know, we will push out a fix for this.

**Comment by Natay** [comment]
This issue has been fixed in the most current deployment.
