### ISSUE TITLE
Preview rendering better than actual render when using HTML tags `details` and `summary`

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/support.bioconductor.org#69]
When answering a question, tags like `details` and `summary` work in the HTML preview but not when you click <kbd> Save </kbd>. 

## preview

![preview_reprex](https://user-images.githubusercontent.com/4392950/116434310-51345e00-a818-11eb-9cff-d379ae7ea078.png)

## actual answer
![actual_not_supported](https://user-images.githubusercontent.com/4392950/116434328-5396b800-a818-11eb-8e5b-cd9d3c201070.png)

**Comment by Natay** [comment]
@LiNk-NY Thank you for letting us know, we have changed our policy so html is escaped in the previews. 

But the strikethrough did have a rendering issue and that has been fixed.
