### ISSUE TITLE
Duplicated badges?

### ISSUE THREAD

**Issue by llrs** [Bioconductor/support.bioconductor.org#7]
When I visit some of the [badges](http://supportupgrade.bioconductor.org/b/list/) like [this one](http://supportupgrade.bioconductor.org/b/view/4f9bafc7/) there is the same people multiple times. 
This might be an error as there seems to be applied to the same person multiple times without any time difference between them.

**Comment by Natay** [comment]
Thanks for letting us know! 

The new codebase picks up missing badges not awarded in the previous database and awards them all at once, giving the impression that the same people are awarded multiple times. We will investigate further before closing this issue.
