### ISSUE TITLE
Strikethrough doesn't work

### ISSUE THREAD

**Issue by jmacdon** [Bioconductor/support.bioconductor.org#70]
Doing either ~~this should be struck through~~ or <del>this should be struck through</del> on the support site results in unrendered text instead of the expected struck through text.

**Comment by jmacdon** [comment]
Haha, but it works here.  I can't even show the actual code I'm using because it gets rendered. I'm wrapping with \~~ or , \<del> blocks

**Comment by Natay** [comment]
Thank you for letting us know, this issue has been fixed.
