### ISSUE TITLE
email API case insensitive  but watched tag email case sensitive 

### ISSUE THREAD

**Issue by lshep** [Bioconductor/support.bioconductor.org#73]
Can we have the case sensitivity be consistent.

**Comment by lshep** [comment]
https://github.com/Bioconductor/BiocCheck/issues/135

**Comment by Natay** [comment]
Thanks for lettings us know, we will have both api endpoints be case insensitive.

**Comment by lshep** [comment]
I think maybe we want case sensitive instead of insensitive?   but I'm up for either as long as it is consistent

**Comment by Natay** [comment]
Yeah we can have them be case sensitive

**Comment by Natay** [comment]
Both of the apis are care sensitive now and consistent with each other.
