### ISSUE TITLE
post tag limit? 

### ISSUE THREAD

**Issue by lshep** [Bioconductor/support.bioconductor.org#74]
I didn't realize there was a limit to the post tag character limit?  Is this intentional and should/can we make it a little bigger? 
![PostLimit](https://user-images.githubusercontent.com/18724380/117823311-54c5dd00-b23b-11eb-96ef-d151e80f72ca.png)

**Comment by lshep** [comment]
Now instead of character limit I have a limit of 5 tags?

**Comment by lshep** [comment]
![5LimitTag](https://user-images.githubusercontent.com/18724380/118641396-1a62bf80-b7a8-11eb-8182-c3cc6a368294.png)

**Comment by Natay** [comment]
This was the case before as well, we found that more than five tags crowds the page on biostars. 
We can increase that limit to 8 to better fit your needs, let us know if it needs to be bumped up more.

**Comment by lshep** [comment]
ok thank you
