### ISSUE TITLE
Cannot create a new NEWS post

### ISSUE THREAD

**Issue by lshep** [Bioconductor/support.bioconductor.org#76]
I just tried to create a new NEWS post for the deadline for Bioconductor awards.  It submitted and showed no errors but did not post to the list.  For now I bumped the old announcement post but the generation of a new post should be looked into

**Comment by Natay** [comment]
Thanks for letting us know, if the content of two posts made by same user are exactly the same it drops to the previous post already made. 

This was done to mitigate duplicate form submissions we saw users make.
