### ISSUE TITLE
Some pages have the `Biostar` title

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/support.bioconductor.org#77]
I was searching for `VariantAnnotation` and clicking on the tag below the first post (after sorting by Date),
I saw a small branding issue here: 

https://support.bioconductor.org/tag/%3Cb%20class=%22match%20term1%22%3E%20VariantAnnotation%3C/b%3E/ 

Also the link returns an empty result. Shouldn't the click return all posts with that Tag? 

![image](https://user-images.githubusercontent.com/4392950/127699747-778b425c-f0b3-4595-b579-5ec00b9652ff.png)

```html
<head>
    <title>        
    Biostar 
    </title>
  ...
</head>
```

**Comment by hpages** [comment]
Looks like another instance of the problem reported in issue #68

**Comment by llrs** [comment]
Biostar still appears on some tab titles like [jobs](https://support.bioconductor.org/t/jobs/)

**Comment by hpages** [comment]
and also [NEWS](https://support.bioconductor.org/t/news/), [TUTORIALS](https://support.bioconductor.org/t/tutorials/), [TAGS](https://support.bioconductor.org/t/), and [USERS](https://support.bioconductor.org/user/list/).
