### ISSUE TITLE
Scam members are now allowed to display profile

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#82]
Starting the last day or two, the Bioconductor Support now has a number of new members who are obvious scammers but are being allowed to display profile text. Until a day or two ago, this was not allowed.

Examples include:
scatadele1, walkerjamier87, tutorchamps0, Tutor Champs1, tutorchamps1718, tutorialsweb, Bright Tutor Singapore, TutorVersal Assignment Help

There are also a very suspicious number of very new users based in Lithuania.

**Comment by Natay** [comment]
Moderators can view all user profile info, regular users see a standard text for these users ( you can view the profiles through an incognito tab to verify )

**Comment by gksmyth** [comment]
Thanks, yes, I see now that non-moderators cannot see the profile information for these recently joined members. I should have checked that myself before posting the issue.

What confused me was the fact that this behavior has changed -- until very recently, even moderaters could not see the profile information for very new members. The profile information for these users has only very recently become visible to me, and I assumed without checking that was true for everyone.
