### ISSUE TITLE
User search strange results

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#9]
Clicking on USERS to top page, then searching for "Gordon" finds 12 users. This includes "Gord Brown" but not "Gordon Smyth".

On the current support site, the same search brings up 15 users with "Gordon Smyth" as first hit.

Searching for "Gordon Smyth" finds 4 users, none of which are called Gordon and all of whom have single-letter names!

**Comment by Natay** [comment]
Users search has been fixed.
